global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wine-api'
    static_configs:
      - targets: ['wine-api:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']